config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root to: 'static_pages#home'
    post '/create-checkout-session', to: 'static_pages#create-checkout-session'


    mount Sidekiq::Web => '/sidekiq'
    mount ActionCable.server => '/cable'

    # APIとサービスの「認証情報」の設定
    get '/auth/google_oauth2/callback', to: 'static_pages#home'
    get  '/signup',  to: 'users#new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    # 資料請求
    get '/catalog_request', to: 'static_pages#catalog_request'

    # 2020/10/21 letter_opener 導入
    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: '/letter_opener'
    end

    resources :users do
      member do
        get :payment_setting
        get :invoices
      end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]

    resources :plans do
      collection do
        get :introduction
      end
    end
    resources :units

    # 支払い方法
    resources :customers do
      member do
        #支払い方法の削除の確認
        get :delete_confirmation
      end
      collection do
        get :fix_payment_method
      end
    end

    # 定期課金
    resources :subscriptions do
      collection do
        get :checkout
        get :success
      end
      member do
        patch :cancel
      end
    end

    # 都度購入
    resources :unit_purchases do
      collection do
        get :checkout
        get :success
      end
    end

    resources :webhook do
      collection do
        post :stripe
      end
    end


  end
end

app/models/user.rb
class User < ApplicationRecord
  # 支払い手段・クレカ
  has_one :customer, dependent: :destroy
  # サブスク
  has_many :subscriptions, dependent: :destroy
  # 都度払い
  has_many :unit_purchases, dependent: :destroy



  # user_idをランダムな数字にする /gem public_uid
  generate_public_uid generator: PublicUid::Generators::NumberSecureRandom.new
  mount_uploader :icon, IconUploader
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  # has_secure_passwordは、'bcrypt'を利用してpassword_digestを生成したり、authenticateメソッドを利用できるようにする。参照：https://railstutorial.jp/chapters/modeling_users?version=5.1#sec-creating_and_authenticating_a_user
  # has_secure_password validations: true
  has_secure_password validations: false
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :profile, length: { maximum: 500 }, allow_nil: true


  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
             BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # アカウントを有効にする
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self.id, self.activation_token).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def lang_code
    'ja'
  end



  # 有料会員かどうか確認する。
  def verify_premium_member?
    # Stripeで契約したか？
    customer.subscriptions.present?
  end

  # public_uid
  def self.find_param(param)
    find_by! public_uid: param
  end

  def to_param
    public_uid
  end

  def g_public_uid
    update(public_uid: SecureRandom.hex(5))
  end

  private

  # メールアドレスをすべて小文字にする
  def downcase_email
    self.email = email.downcase
  end

  # 有効化トークンとダイジェストを作成および代入する
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,]
  before_action :correct_user,   only: [:edit, :update, :payment_setting, :invoices]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find_param(params[:id])
    @subscriptions = @user.customer&.subscriptions
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      @user.send_activation_email
      flash[:success] = t('users.creating_account_succeeded')
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_param(params[:id])
    @breadcrumb_hash = {t('users.my_page') => user_path(@user),
                        'アカウント設定' => ''}
  end

  def update
    @user = User.find_param(params[:id])
    if @user.update(user_params)
      flash[:success] = 'プロフィールを更新しました。'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find_param(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def payment_setting
    @subscriptions = @user&.customer&.subscriptions
    @customer = @user.customer
    @stripe_card = @customer&.stripe_card
    @breadcrumb_hash = {t('users.my_page') => user_path(@user),
                        'お支払い設定' => ''}
  end


  def invoices
    customer = @user.customer
    @invoices = Stripe::Invoice.list(customer: customer.stripe_customer_id)
    @breadcrumb_hash = {t('users.my_page') => user_path(@user),
                        'お支払い設定' => payment_setting_user_path(@user),
                        '領収書/請求書' => ''}
  end



  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :profile, :profile, :icon, :remove_icon,
                                 :password_confirmation)
  end

  # beforeアクション

  # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find_param(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # 管理者かどうか確認
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのアイコン画像を返す
  def icon_for(user, size: 80)
    if user.present? && user.icon_url.present?
      image_tag(user.icon_url, alt: user.name,
                # メールだとbootstrapは効かないので、styleでborder-radiusを指定する。
                size: "#{size}x#{size}", style: 'border-radius: 50%;',
                src: 'Image Not Found',
                onerror: "this.error=null;this.src='#{NOT_FOUND_ICON}'")
    elsif user.present?
      gravatar_for(user, size: size)
    else
      image_tag(NOT_FOUND_ICON,
                alt: t('users.anonymous_user'),
                size: "#{size}x#{size}", style: 'border-radius: 50%;',)
    end
  end

  # 渡されたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    size = options[:size]
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar", style: 'border-radius: 50%;')
  end
end

app/views/users/_aside.html.erb
<aside class="col-md-4">

  <section class="mt-3 mb-5">
    <div class="text-center">
      <%= icon_for @user %>
    </div>
    <h4 class="text-center font-weight-bold mt-3">
      <%= title @user.name %>
    </h4>
    <div class="my-3"><%= simple_format @user.profile %></div>
  </section>

  <% if @user == current_user || current_user&.admin? %>

    <%= link_to edit_user_path(@user), class: 'btn btn-solid mt-3 mb-4 d-block' do %>
      アカウント設定
    <% end %>
    <%= link_to payment_setting_user_path(@user), class: 'btn btn-solid mt-3 mb-4 d-block' do %>
      お支払い設定
    <% end %>
    <%= link_to logout_path, method: :delete, class: 'btn btn-solid mt-3 mb-4 d-block main-loading-show-btn' do %>
      ログアウト
    <% end %>
  <% end %>

</aside>

app/views/users/_edit_fields.html.erb
<div class="my-4 text-center">
  <%= icon_for f.object %>
</div>
<div class="my-4 text-center">
  <%= f.file_field :icon, accept: 'image/jpeg,image/gif,image/png' %>
  <% if f.object.icon? %>
    <label class="d-block mt-3">
      <%= f.check_box :remove_icon %>
      画像を削除
    </label>
  <% end %>
</div>

<%= f.label :name, "名前", class: 'small' %>
<%= f.text_field :name, class: "form-control mb-4", placeholder: "ユーザー名を入力してください。" %>


<%= f.label :profile, "プロフィール", class: 'small' %>
<%= f.text_area :profile, class: "form-control mb-4", placeholder: "500文字以内でプロフィールを入力してください。", rows: 4 %>


<!--
<div class="custom-control custom-switch my-3">
  <#%= f.check_box :notification_deliver, class: 'custom-control-input', id: 'notificationDeliver' %>
  <label class="custom-control-label" for="notificationDeliver">メールによる通知を受け取る</label>
</div>
-->


<h3 class="text-center text-success font-weight-bold mt-5 mb-3">認証設定</h3>

<%= f.label :email, "メールアドレス", class: 'small' %>
<%= f.email_field :email, class: "form-control mb-4", placeholder: "メールアドレスを入力してください。" %>

<%= f.label :password, "新しいパスワード", class: 'small' %>
<%= f.password_field :password, class: "form-control mb-4", placeholder: "半角英数字６文字以上" %>

<%= f.label :password_confirmation, "パスワード確認", class: 'small' %>
<%= f.password_field :password_confirmation, class: "form-control mb-4", placeholder: "もう一度パスワードを入力してください。" %>

app/views/users/_sign_up_form.html.erb
<% @user = User.new if @user.blank? %>
<%= form_with model: @user, local: true do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name, "#{t 'static_pages.name'}", class: "text-left small text-secondary" %>
  <%= f.text_field :name, class: "form-control mb-4", placeholder: 'ユーザー名を入力してください。' %>

  <%= f.label :email, "#{t 'static_pages.email'}", class: "text-left small text-secondary" %>
  <%= f.email_field :email, class: "form-control mb-4", placeholder: 'メールアドレスを入力してください。' %>

  <%= f.label :password, "#{t 'static_pages.password'}", class: "text-left small text-secondary" %>
  <%= f.password_field :password, class: "form-control mb-4", placeholder: 'パスワードを入力してください。' %>


  <%= f.submit "#{t 'static_pages.submit_signup'}", class: "btn btn-solid main-loading-show-btn w-100 mt-4" %>

<% end %>


<p class="my-5 font-weight-bold"><%= t 'static_pages.do_you_have_an_account?' %> <%= link_to t('static_pages.login'), login_path, style: 'color: #f79c4f;' %></p>

app/views/users/edit.html.erb
<% set_meta_tags noindex: true %>


<div class="d-block mt-4"></div>
<%= render 'layouts/breadcrumb', items_hash: @breadcrumb_hash %>

<div class="container bg-white pt-5 pb-5 my-5">

  <div class="row justify-content-md-center">

    <div class="col-md-6">

      <h1 class="font-weight-bold text-center"><%= title 'アカウント設定' %></h1>
      <%= form_with model: @user, local: true do |f| %>
        <%= render "shared/error_messages", object: f.object %>

        <%= render 'users/edit_fields', f: f %>


        <%= f.submit "更新する", class: "btn btn-solid w-100 main-loading-show-btn my-5" %>

      <% end %>

      <div class="d-block py-5"></div>
      <!--
      <p><a href="<#%= withdrawal_confirmation_user_url(@user) %>" class="btn btn-sm btn-border-gray">アカウントを消去する</a></p>
      -->


      <script type="text/javascript">
          $('#user_icon').bind('change', function () {
              var size_in_megabytes = this.files[0].size / 1024 / 1024;
              if (size_in_megabytes > 5) {
                  alert('最大画像サイズは2MBです。より小さなファイルを選択して下さい。');
              }
          });
      </script>
    </div>
  </div>
</div>

app/views/users/invoices.html.erb
<% set_meta_tags noindex: true %>

<div class="my-3">
  <%= render 'layouts/breadcrumb', items_hash: @breadcrumb_hash %>

  <div class="container bg-white pt-5 pb-5 my-5">
    <div class="row justify-content-md-center">

      <div class="col-md-6">

        <h1 class="text-center font-weight-bold">領収書/請求書</h1>

        <% if @invoices.blank? %>
          <h3 class="text-center"><%= "領収書/請求書はありません。" %></h3>
        <% else %>

          <div class="row row-height">
            <%= render partial: 'invoices/invoice', collection: @invoices, as: 'invoice' %>
          </div>
        <% end %>

      </div>

    </div>
  </div>

</div>

app/views/users/new.html.erb
<% provide(:title, '会員登録') %>

<div class="container bg-white pt-5 pb-5 my-5">

  <h1 class="text-center font-weight-bold"><%= title t('static_pages.signup') %></h1>

  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= render "users/sign_up_form" %>
    </div>
  </div>
</div>

app/views/users/payment_setting.html.erb
<% set_meta_tags noindex: true %>
<div class="d-block mt-4"></div>
<%= render 'layouts/breadcrumb', items_hash: @breadcrumb_hash %>

<div class="container bg-white pt-5 pb-5 my-5">
  <div class="row justify-content-md-center">

    <div class="col-md-6">

      <h1 class="text-center font-weight-bold">ご加入プラン</h1>

      <% if @subscriptions.blank? %>

        <h3 class="text-center my-5">未加入です。</h3>

      <% else %>
        <%= render partial: 'subscriptions/item', collection: @subscriptions, as: 'subscription' %>
      <% end %>


      <div class="d-block py-3"></div>

      <h1 class="text-center font-weight-bold mt-5">お支払方法</h1>

      <% if @customer.present? %>
        <%= render 'customers/item', customer: @customer, stripe_card: @stripe_card %>
      <% else %>
        <%= render 'customers/stripe_element_form', customer: Customer.new %>
      <% end %>



      <!--
      <#% if @customer.present? %>
        <#%= link_to invoices_user_path(@user) do %>
          <div class="btn btn btn-border-gray my-4">領収書 / 請求書をみる</div>
        <#% end %>
      <#% end %>
      -->


    </div>


  </div>

</div>

app/views/users/show.html.erb
<% set_meta_tags noindex: true %>


<div class="container bg-white pt-5 pb-5 my-5">
  <div class="px-3">
    <div class="row" style="min-height: 840px;">

      <%= render "users/aside" %>

      <div class="col-md-8">

        <!--
        <h1 class="text-center font-weight-bold">
          <i class="fas fa-graduation-cap mr-2"></i>学習記録
        </h1>

        <h3 class="text-secondary font-weight-bold my-5 text-center">まだ学習記録がありません。</h3>
        <div class="d-block py-3"></div>
        -->


        <h1 class="text-center font-weight-bold mt-5">
          ご契約プラン
        </h1>

        <% if @subscriptions.blank? %>
          <div class="plans mt-5">
            <div class="plan-table plan-free px-2 my-5">
              <table>
                <%= render 'plans/explanation_1' %>
                <tr>
                  <td>
                    <%= link_to '契約する', checkout_subscriptions_path(plan_number: 1),
                                class: 'btn btn-solid main-loading-show-btn w-100',
                                data: { "turbolinks" => false } %>
                  </td>
                </tr>
              </table>
            </div>
            <div class="plan-table plan-premium px-2 my-5">
              <table>
                <%= render "plans/explanation_2" %>
                <tr>
                  <td>
                    <%= link_to '契約する', checkout_subscriptions_path(plan_number: 2),
                                class: 'btn btn-solid main-loading-show-btn w-100',
                                data: { "turbolinks" => false } %>
                  </td>
                </tr>
              </table>
            </div>

            <div class="plan-table plan-premium px-2 my-5">
              <table>
                <%= render "plans/explanation_3" %>
                <tr>
                  <td>
                    <%= link_to '契約する', checkout_subscriptions_path(plan_number: 3),
                                class: 'btn btn-solid main-loading-show-btn w-100',
                                data: { "turbolinks" => false } %>
                  </td>
                </tr>
              </table>
            </div>
          </div>

        <% else %>

          <% @subscriptions.each do |subscription| %>
            <%= render 'subscriptions/item', subscription: subscription %>
          <% end %>

        <% end %>

      </div>
    </div>

  </div>


</div>