config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root to: 'static_pages#home'
    post '/create-checkout-session', to: 'static_pages#create-checkout-session'


    mount Sidekiq::Web => '/sidekiq'
    mount ActionCable.server => '/cable'

    # APIとサービスの「認証情報」の設定
    get '/auth/google_oauth2/callback', to: 'static_pages#home'
    get  '/signup',  to: 'users#new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    # 資料請求
    get '/catalog_request', to: 'static_pages#catalog_request'

    # 2020/10/21 letter_opener 導入
    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: '/letter_opener'
    end

    resources :users do
      member do
        get :payment_setting
        get :invoices
      end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]

    resources :plans do
      collection do
        get :introduction
      end
    end
    resources :units

    # 支払い方法
    resources :customers do
      member do
        #支払い方法の削除の確認
        get :delete_confirmation
      end
      collection do
        get :fix_payment_method
      end
    end

    # 定期課金
    resources :subscriptions do
      collection do
        get :checkout
        get :success
      end
      member do
        patch :cancel
      end
    end

    # 都度購入
    resources :unit_purchases do
      collection do
        get :checkout
        get :success
      end
    end

    resources :webhook do
      collection do
        post :stripe
      end
    end


  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user, optional: true
  has_many :subscriptions, dependent: :destroy
  before_destroy :delete_stripe_customer, prepend: true

  # 引数のStripeToken（クライアント側で取得）を使って、引数のuserにcustomerを作成する。
  def self.create_customer(user, stripe_token)
    stripe_customer = Stripe::Customer.create(email: user.email,
                                              source: stripe_token)
    return nil if stripe_customer.blank?
    customer = Customer.new(stripe_customer_id: stripe_customer.id,
                            user_id: user.id,)
    customer.save!
  end

  def update_customer(stripe_token)
    customer = Stripe::Customer.update(self.stripe_customer_id,
                                       { source: stripe_token })
    update(stripe_customer_id: customer.id)
  end

  def retrieve_stripe_customer
    begin
      Stripe::Customer&.retrieve(self.stripe_customer_id)
    rescue StandardError
      nil
    end
  end

  # 決済に利用したカードのリスト
  # ref: https://stripe.com/docs/api/payment_methods/customer
  def stripe_cards
    Stripe::Customer.list_payment_methods(
      self.stripe_customer_id,
      { type: 'card' },
      )&.data rescue nil
  end

  # メインのカード情報
  def stripe_card
    stripe_cards&.first&.card
  end

  # チェックアウトの支払い成功後のsessionを利用してcustomerを作成or更新数r
  def self.create_or_update_with_session(user:, session:)
    # ユーザーが支払い情報を作成していなければ、作成する
    if (customer = user.customer)
      customer.update(stripe_customer_id: session.customer)
    else
      # stripe_customer = Stripe::Customer.retrieve(session.customer)
      customer = Customer.create(stripe_customer_id: session.customer,
                                 user: user)
    end
    customer
  end

  def self.find_by_webhook(event)
    customer = event.data.object
    self.find_by(stripe_customer_id: customer['id'])
  end

  def self.find_by_payment_intent(event)
    payment_intent = event.data.object
    self.find_by(stripe_customer_id: payment_intent['customer'])
  end

  def self.find_user_by_webhook(event)
    self.find_by_webhook(event)&.user rescue nil
  end

  private

  # Stipe側のデータも消し込む
  def delete_stripe_customer
    Stripe::Customer.delete(stripe_customer_id)
  rescue StandardError
    nil
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: %i[edit destroy update delete_confirmation]

  def create
    if current_user.customer.blank? && params[:stripeToken].present?
      begin
        Customer.create_customer(current_user, params[:stripeToken])
        flash[:success] = 'お支払い方法を登録しました。'
        redirect_to payment_setting_user_url(current_user)
      rescue Stripe::CardError => e
        flash[:danger] = "決済(stripe)でエラーが発生しました。#{e.message}"
        redirect_to payment_setting_user_url(current_user)
      rescue Stripe::InvalidRequestError => e
        flash[:danger] = "決済(stripe)でエラーが発生しました（InvalidRequestError）#{e.message}"
        redirect_to payment_setting_user_url(current_user)

        # Authentication with Stripe's API failed(maybe you changed API keys recently)
      rescue Stripe::AuthenticationError => e
        flash[:danger] = "決済(stripe)でエラーが発生しました（AuthenticationError）#{e.message}"
        redirect_to payment_setting_user_url(current_user)

        # Network communication with Stripe failed
      rescue Stripe::APIConnectionError => e
        flash[:danger] = "決済(stripe)でエラーが発生しました（APIConnectionError）#{e.message}"
        redirect_to payment_setting_user_url(current_user)

        # Display a very generic error to the user, and maybe send yourself an email
      rescue Stripe::StripeError => e
        flash[:danger] = "決済(stripe)でエラーが発生しました（StripeError）#{e.message}"
        redirect_to payment_setting_user_url(current_user)

        # stripe関連以外でエラーが起こった場合
      rescue StandardError => e
        flash[:danger] = "エラーが発生しました#{e.message}"
        redirect_to payment_setting_user_url(current_user)
      end
    else
      flash[:danger] = 'すでにお支払い方法が登録されています。'
      redirect_to payment_setting_user_url(current_user)
    end
  end

  def edit
    @title = 'お支払い方法の更新'
    @breadcrumb_hash =  { 'マイページ' => user_path(current_user),
                          'お支払い設定' => payment_setting_user_path(current_user),
                          @title => '' }
  end

  def update
    p params[:stripeToken]
    @customer.update_customer(params[:stripeToken])
    flash[:success] = 'お支払い情報を更新しました。'
    redirect_to payment_setting_user_url(current_user)
  rescue Stripe::CardError => e
    flash[:danger] = "決済(stripe)でエラーが発生しました。#{e.message}"
    redirect_to edit_customer_url(@customer)
  rescue Stripe::InvalidRequestError => e
    flash[:danger] = "決済(stripe)でエラーが発生しました（InvalidRequestError）#{e.message}"
    redirect_to edit_customer_url(@customer)

    # Authentication with Stripe's API failed(maybe you changed API keys recently)
  rescue Stripe::AuthenticationError => e
    flash[:danger] = "決済(stripe)でエラーが発生しました（AuthenticationError）#{e.message}"
    redirect_to edit_customer_url(@customer)

    # Network communication with Stripe failed
  rescue Stripe::APIConnectionError => e
    flash[:danger] = "決済(stripe)でエラーが発生しました（APIConnectionError）#{e.message}"
    redirect_to edit_customer_url(@customer)

    # Display a very generic error to the user, and maybe send yourself an email
  rescue Stripe::StripeError => e
    flash[:danger] = "決済(stripe)でエラーが発生しました（StripeError）#{e.message}"
    redirect_to edit_customer_url(@customer)

    # stripe関連以外でエラーが起こった場合
  rescue StandardError => e
    flash[:danger] = "エラーが発生しました#{e.message}"
    redirect_to edit_customer_url(@customer)
  end

  def delete_confirmation
    @user = @customer.user
    @title = 'お支払い方法を消去'
    @breadcrumb_hash = {t('users.my_page') => user_path(@user),
                        'お支払い設定' => payment_setting_user_path(@user),
                         @title => ''}
  end

  def destroy
    @customer.destroy
    flash[:success] = 'お支払い方法を消去しました。'
    redirect_to payment_setting_user_url(current_user)
  end

  # カードの期限切れや与信落ち、紛失届によって決済が失敗した場合に送られるメールにリンクされている
  # カードの更新ページ
  def fix_payment_method
    @user = current_user
    @customer = @user.customer
    if @customer.present?
      flash[:warning] = 'カード情報を更新してください。'
      redirect_to edit_customer_url(@customer)
    else
      redirect_to payment_setting_user_path(@user)
    end
  end

  private

  def correct_user
    @customer = Customer.find(params[:id])
    if @customer.user == current_user || @customer&.chapter&.user == current_user
      true
    else
      redirect_to root_url
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_item.html.erb
<% if customer.present? %>
  <div class="card border-success my-3 py-3 w-100">
    <div class="card-body text-center">
      <% if stripe_card.present? %>
        <h5 class="card-title">**** **** **** <%= stripe_card&.last4 %></h5>
        <p class="card-text text-secondary">有効期限：<%= "#{stripe_card&.exp_year}/#{stripe_card&.exp_month}" %></p>
        <p class="card-text text-secondary"><%= stripe_card&.brand %></p>
        <p class="card-text text-secondary"><%= stripe_card&.country %></p>
      <% else %>
        <h5 class="card-title">Invalid Card ID</h5>
      <% end %>

      <%= link_to edit_customer_path(customer), data: { "turbolinks" => false }, class: 'btn btn btn-border-gray w-100 my-2' do %>
        支払い方法を更新する
      <% end %>

      <!--
      <#%= link_to delete_confirmation_customer_path(customer), class: 'btn btn btn-border-gray w-100 my-2' do %>
        　支払い方法を消去する　
      <#% end %>
      -->

    </div>

  </div>

<% end %>

app/views/customers/_stripe_element_form.html.erb
<!-- Stripe elementsのExample 4 と、https://qiita.com/tomokazu0112/items/89f69c47761ac782ce13 を組み合わせたフォーム-->
<!-- example 4： https://stripe.dev/elements-examples/ -->

<div class="cell example example4" id="example-4">
  <%= form_with model: customer, local: true, id: 'payment-form' do %>
    <form class="mx-auto">
      <div id="example4-paymentRequest">
        <!--Stripe paymentRequestButton Element inserted here-->
      </div>

      <fieldset>
        <legend class="card-only" data-tid="elements_examples.form.pay_with_card">カードを登録</legend>
        <legend class="payment-request-available" data-tid="elements_examples.form.enter_card_manually">Or enter card
          details
        </legend>
        <div class="container">

          <div id="example4-card">
            <!-- Stripe Element がここに入ります。 -->
          </div>
          <button type="submit" data-tid="elements_examples.form.donate_button" class="font-weight-bold">登録する</button>
        </div>
      </fieldset>

      <!-- Element のエラーを入れます。 -->
      <div id="card-errors" role="alert"></div>
    </form>
  <% end %>


</div>

<script src="https://js.stripe.com/v3"></script>
<script>
    (function () {
        "use strict";

        var stripe = Stripe('<%= Rails&.configuration&.stripe[:publishable_key] %>');
        var elements = stripe.elements({
            fonts: [
                {
                    cssSrc: "https://rsms.me/inter/inter.css"
                }

            ],
            // Stripe's examples are localized to specific languages, but if
            // you wish to have Elements automatically detect your user's locale,
            // use `locale: 'auto'` instead.
            locale: 'auto'
        });

        /**
         * Card Element
         */
        var card = elements.create("card", {
            style: {
                base: {
                    color: "#32325D",
                    fontWeight: 500,
                    fontFamily: "Inter, Open Sans, Segoe UI, sans-serif",
                    fontSize: "16px",
                    fontSmoothing: "antialiased",

                    "::placeholder": {
                        color: "#CFD7DF"
                    }
                },
                invalid: {
                    color: "#E25950"
                },

            },
            // 郵便番号の入力を取り除く / https://stripe.com/docs/js/elements_object/create_element?type=card#elements_create-options-hidePostalCode
            hidePostalCode: true,

        });

        card.mount("#example4-card");


        // stripeTokenを送信するための処理 / https://qiita.com/tomokazu0112/items/89f69c47761ac782ce13

        // Handle real-time validation errors from the card Element.
        // バリデーションエラーの表示
        card.addEventListener('change', function (event) {
            var displayError = document.getElementById('card-errors');
            if (event.error) {
                displayError.textContent = event.error.message;
            } else {
                displayError.textContent = '';
            }
        });

        // Handle form submission.
        // submitボタンが押されたときに、stripeTokenを作成する。
        var form = document.getElementById('payment-form');
        form.addEventListener('submit', function (event) {
            event.preventDefault();

            stripe.createToken(card).then(function (result) {
                if (result.error) {
                    // Inform the user if there was an error.
                    var errorElement = document.getElementById('card-errors');
                    errorElement.textContent = result.error.message;
                } else {
                    // Send the token to your server.
                    stripeTokenHandler(result.token);
                }
            });
        });

        // Submit the form with the token ID.
        // stripeTokenをhiddenFieldに格納してサーバーサイドに送信する。
        function stripeTokenHandler(token) {
            // Insert the token ID into the form so it gets submitted to the server
            var form = document.getElementById('payment-form');
            var hiddenInput = document.createElement('input');
            hiddenInput.setAttribute('type', 'hidden');
            hiddenInput.setAttribute('name', 'stripeToken');
            hiddenInput.setAttribute('value', token.id);
            form.appendChild(hiddenInput);

            // Submit the form
            form.submit();
        }

    })();
</script>

app/views/customers/delete_confirmation.html.erb
<div class="d-block mt-4"></div>
<%= render 'layouts/breadcrumb_top', items_hash: @breadcrumb_hash %>

<div class="container bg-white pt-5 pb-5 my-5">
  <div class="row justify-content-md-center">

    <div class="col-md-6">


      <h1 class="text-center font-weight-bold mb-4"><%= title @title %></h1>

      <p>
        お支払い方法を変更したい場合や、お支払い用のカードを変更したい場合は、<%= link_to 'こちらのページ', edit_customer_url(@customer), class: 'text-success' %>
        から行なってください。
      </p>
      <p>お支払い方法を削除されると領収書の確認などができなくなります。</p>
      <p>復元などもできかねますので、あらかじめご理解ご了承くださいませ。</p>

      <% if @customer.subscriptions.present? %>
        <p>また現在、ご契約中のプランがございますので、もしお支払い方法を削除したい場合には、まずはご契約しているプランの解約を行ってください。</p>
        <%= link_to ' 契約中のプランを解約する', payment_setting_user_path(current_user),
                    class: 'btn btn btn-danger font-weight-bold d-block my-4 w-100' %>

      <% else %>
        <p>本当にお支払い方法を削除しますか？</p>
        <%= link_to customer_path(@customer), method: :delete,
                    class: "btn btn btn-danger d-block w-100 my-5 font-weight-bold",
                    data: { confirm: '本当に支払い方法を削除してもよろしいですか?',
                            cancel: 'キャンセル',
                            commit: '削除する' }, title: '削除確認' do %>
          支払い方法を消去する
        <% end %>

      <% end %>
    </div>

  </div>
</div>

app/views/customers/edit.html.erb
<div class="my-3">

  <%= render 'layouts/breadcrumb', items_hash: @breadcrumb_hash %>

  <div class="container bg-white pt-5 pb-5 my-5">
    <div class="row justify-content-md-center">

      <div class="col-md-6">
        <h1 class="text-center font-weight-bold"><%= @title %></h1>
        <%= render 'customers/stripe_element_form', customer: @customer %>

      </div>
    </div>
  </div>

</div>