config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root to: 'static_pages#home'
    post '/create-checkout-session', to: 'static_pages#create-checkout-session'


    mount Sidekiq::Web => '/sidekiq'
    mount ActionCable.server => '/cable'

    # APIとサービスの「認証情報」の設定
    get '/auth/google_oauth2/callback', to: 'static_pages#home'
    get  '/signup',  to: 'users#new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    # 資料請求
    get '/catalog_request', to: 'static_pages#catalog_request'

    # 2020/10/21 letter_opener 導入
    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: '/letter_opener'
    end

    resources :users do
      member do
        get :payment_setting
        get :invoices
      end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]

    resources :plans do
      collection do
        get :introduction
      end
    end
    resources :units

    # 支払い方法
    resources :customers do
      member do
        #支払い方法の削除の確認
        get :delete_confirmation
      end
      collection do
        get :fix_payment_method
      end
    end

    # 定期課金
    resources :subscriptions do
      collection do
        get :checkout
        get :success
      end
      member do
        patch :cancel
      end
    end

    # 都度購入
    resources :unit_purchases do
      collection do
        get :checkout
        get :success
      end
    end

    resources :webhook do
      collection do
        post :stripe
      end
    end


  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :plan
  belongs_to :customer
  belongs_to :user, optional: true
  # prepend ref: https://tech.actindi.net/2016/01/07/3661113852
  before_destroy :delete_stripe_subscription, prepend: true


  # セッション生成
  def self.create_session(user:, plan:, locale:)
    return if user.blank? || plan.blank? || locale.blank?

    success_url = Rails.application.routes.url_helpers.root_url(locale: locale) + "/subscriptions/success?plan_number=#{plan.reference_number}&session_id={CHECKOUT_SESSION_ID}"
    cancel_url = Rails.application.routes.url_helpers.user_url(user, locale: locale)
    # すでに一度トライアルを経験している場合にはnil
    trial_period_days = user.trial_used ? nil : plan.trial_period_days_count
    if (customer = user.customer)
      Stripe::Checkout::Session.create({
                                         customer: customer.stripe_customer_id,
                                         line_items: [{
                                                        price: plan.stripe_price_id,
                                                        quantity: 1,
                                                      }],
                                         payment_method_types: [
                                           'card',
                                         ],
                                         mode: 'subscription',
                                         subscription_data: { trial_period_days: trial_period_days },
                                         locale: locale,
                                         success_url: success_url,
                                         cancel_url: cancel_url,
                                       })
    else
      Stripe::Checkout::Session.create({
                                         customer_email: user.email,
                                         line_items: [{
                                                        price: plan.stripe_price_id,
                                                        quantity: 1,
                                                      }],
                                         payment_method_types: [
                                           'card',
                                         ],
                                         mode: 'subscription',
                                         subscription_data: { trial_period_days: trial_period_days },
                                         locale: locale,
                                         success_url: success_url,
                                         cancel_url: cancel_url,
                                       })
    end
  end

  def self.create_with_session(user:, plan:, customer:, session:)
    annual = plan.interval == 'year'
    stripe_subscription = Stripe::Subscription.retrieve(
      session.subscription,
    )
    Subscription.create!(customer: customer,
                         plan: plan,
                         user: user,
                         stripe_subscription_id: session.subscription,
                         trial_start: stripe_subscription.trial_start,
                         trial_end: stripe_subscription.trial_end,
                         annual: annual)
  end


  def stripe_subscription
    Stripe::Subscription.retrieve(
      self.stripe_subscription_id,
    )
  end

  # サブスクリプションをキャンセル
  def cancel_subscription
    stripe_subscription = Stripe::Subscription.cancel(
      self.stripe_subscription_id,
    )
    update(canceled: true,
           period_end: stripe_subscription['current_period_end'])
  end

  # 従量課金のquantityを増減させたり、確認するには、subscription_item（si）が必要。
  # ref: https://qiita.com/_akira19/items/4688ebaf87b44462baf2
  def stripe_subscription_item_list
    subscription_item_list = Stripe::SubscriptionItem.list(
      subscription: self.stripe_subscription_id
    )
    subscription_item_list
  end

  # si_xxxを取得する
  def stripe_subscription_item_ids
    list = self.stripe_subscription_item_list
    data_ary = list.data
    data_ary&.map { |data| data.id }
  end

  def stripe_subscription_item
    ids = self.stripe_subscription_item_ids
    Stripe::SubscriptionItem.retrieve(
      ids.first,
    )
  end

  # Schoolプランの従量課金の量を更新する ref: https://stripe.com/docs/billing/subscriptions/usage-based?locale=ja-JP#report
  def update_quantity(stripe_si_id, usage_quantity)
    return if stripe_si_id.blank? || usage_quantity.blank?

    timestamp = Time.now.to_i
    # The idempotency key allows you to retry this usage record call if it fails.
    idempotency_key = SecureRandom.hex(8)

    begin
      Stripe::SubscriptionItem.create_usage_record(
        stripe_si_id,
        {
          quantity: usage_quantity,
          timestamp: timestamp,
          action: 'set'
        }, {
          idempotency_key: idempotency_key
        }
      )
    rescue Stripe::StripeError => e
      puts "Usage report failed for item #{stripe_si_id}:"
      puts "#{e.error.message} (idempotency key: #{idempotency_key})"
    end
  end

  # ユニット数を更新する
  def update_stripe_on_usage(units_count)
    ids = stripe_subscription_item_ids
    update_quantity(ids.first, units_count)
    # ref: https://qiita.com/_akira19/items/4688ebaf87b44462baf2
  end

  def trial_ended?
    return true if self.trial_end.blank?

    unix_time_now = Time.now.to_i
    self.trial_end < unix_time_now
  end

  def trial_start_time
    Time.at(self.trial_start)
  end

  def trial_end_time
    Time.at(self.trial_end)
  end

  # サブスクを契約した本人かを確認する
  def correct_user?(user)
    self.customer.user == user
  end

  def self.find_by_webhook(event)
    subscription = event.data.object
    self.find_by(stripe_subscription_id: subscription['id'])
  end

  def self.find_by_sub_schedule(event)
    subscription_schedule = event.data.object
    self.find_by(stripe_subscription_id: subscription_schedule['subscription'])
  end

  def self.find_user_by_webhook(event)
    self.find_by_webhook(event)&.user rescue nil
  end

  def period_end_day
    Time.at(self.period_end).strftime("%Y/%m/%d")
  end

  # 有効期限の切れたサブスクを削除する。
  def self.destroy_expired_subscriptions
    unit_time_now = Time.current.to_i
    Subscription.where("canceled = ? AND period_end < ?", true, unit_time_now).destroy_all
  end

  private

  def delete_stripe_subscription
    # Stripeの課金データを削除
    begin
      Stripe::Subscription&.delete(stripe_subscription_id)
    rescue StandardError
      nil
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user, only: [:index]
  before_action :correct_user, only: %i[destroy update show edit cancel]

  def index
    @subscriptions = Subscription.all
  end

  def checkout
    @plan = Plan.find_by(reference_number: params[:plan_number])
    if @plan.blank?
      flash[:danger] = '無効なプランです。'
      redirect_to root_url
    end
    @session = Subscription.create_session(user: current_user, plan: @plan, locale: @locale)
  end

  def success
    @plan = Plan.find_by(reference_number: params[:plan_number])
    if @plan.blank? || params[:session_id].blank?
      flash[:danger] = '決済できませんでした。'
      redirect_to users_url(current_user)
    end
    session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @customer = Customer.create_or_update_with_session(user: current_user, session: session)
    @subscription = Subscription.create_with_session(user: current_user, plan: @plan,
                                                     customer: @customer, session: session)
    # ユーザーをプレミアム会員にする。
    current_user.assign_attributes(trial_used: true)
    current_user.save(validate: false)
    # 決済完了のメールの送信
    PaymentMailer.make_subscription(@subscription.id).deliver_now
    flash[:success] = 'ご登録が完了いたしました。誠にありがとうございます！'
    redirect_to current_user
  end



  def edit
    @plan = @subscription.plan
    @stripe_subscription = @subscription.stripe_subscription
    @unit = @plan.unit
    @unit_purchases = current_user.unit_purchases.where(unit: @unit).order(created_at: :desc)
    @title = 'プラン設定'
    @user = @subscription.user
    @breadcrumb_hash = {t('users.my_page') => user_path(@user),
                        'お支払い設定' => payment_setting_user_path(@user),
                        'プラン設定' => ''}
  end

  # 追加授業の申し込み
  def update
    units_count = params[:subscription][:units_count].to_i
    if units_count.present?
      @subscription.update(units_count: units_count)
      @subscription.update_stripe_on_usage(units_count)
      flash[:success] = 'プランの更新を完了しました。'
      redirect_to current_user
    else
      flash[:success] = 'プランの更新に失敗しました。'
      redirect_to current_user
    end
  end

  def show
    @subscription = Subscription.find(params[:id])
    @chapter = @subscription.chapter
    @breadcrumb_hash = { 'マイページ' => user_path(current_user),
                         'お支払い設定' => payment_setting_user_path(current_user),
                         'ご解約' => '' }
  end

  def cancel
    @subscription.cancel_subscription
    PaymentMailer.cancel_subscription(@subscription.id).deliver_now
    flash[:success] = "プランを解約しました。"
    redirect_to edit_subscription_url(@subscription)
  end

  private

  def correct_user
    @subscription = Subscription.find(params[:id])
    if @subscription.correct_user?(current_user)
      true
    else
      redirect_to root_url
    end
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_cancel_btn.html.erb
<% if stripe_subscription.present? %>
  <% status = stripe_subscription['status'] %>
  <% if status == 'canceled' %>
    <p class="small text-secondary">状態： 解約済</p>
  <% else %>

    <!-- Button trigger modal -->
    <a class="text-danger small" data-toggle="modal" data-target="#subscriptionCancellation">
      解約する
    </a>

    <!-- Modal -->
    <div class="modal fade" id="subscriptionCancellation" tabindex="-1" role="dialog" aria-labelledby="subscriptionCancellationLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title font-weight-bold" id="subscriptionCancellationLabel">確認画面</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= subscription.plan.nickname %>を解約いたします。よろしいですか？
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary font-weight-bold" data-dismiss="modal">キャンセル</button>
            <%= form_with model: subscription, url: cancel_subscription_path(subscription), local: true do |f| %>
              <%= f.submit '解約する', class: 'btn btn-danger main-loading-show-btn' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  <% end %>

<% end %>

app/views/subscriptions/_contract_status.html.erb
<% if stripe_subscription.present? %>
  <% start_time = Time.at(stripe_subscription['current_period_start']).strftime("%Y/%m/%d") %>
  <% end_time = Time.at(stripe_subscription['current_period_end']).strftime("%Y/%m/%d") %>
  <% status = stripe_subscription['status'] %>

  <p class="small text-secondary">
    開始日：<%= start_time %>
    <br>
    <% if status == 'canceled' %>
      終了日：
    <% else %>
      次回請求日：
    <% end %>
    <%= end_time %>
    <br>
  </p>
<% end %>

app/views/subscriptions/_item.html.erb
<% plan = subscription.plan %>
<% stripe_subscription = subscription.stripe_subscription %>
<div class="my-3">

  <div class="card">
    <div class="card-header font-weight-bold">
      <%= plan.nickname %>
    </div>
    <div class="card-body">
      <p>料金：<%= plan.amount %>円/月</p>

      <%= render "subscriptions/contract_status", stripe_subscription: stripe_subscription %>
      <% if request.path == edit_subscription_path(subscription) %>
        <%= render 'subscriptions/cancel_btn', subscription: subscription, stripe_subscription: stripe_subscription %>
      <% else %>
        <a href="<%= edit_subscription_path(subscription) %>" class="btn btn btn-success w-100 text-white">プラン設定</a>
      <% end %>
    </div>
  </div>
</div>

app/views/subscriptions/checkout.html.erb
<div class="container bg-white pt-5 pb-5 my-5">
  <div class="text-center">
    <img src="<%= LOADING_GIF %>" alt="loading">
  </div>
</div>


<script src="https://js.stripe.com/v3"></script>

<script>
    var stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>'); // ()内には公開可能キーを記述
    stripe.redirectToCheckout({
        sessionId: '<%= @session.id %>'
    }).then(function (result) {
    });
</script>

app/views/subscriptions/edit.html.erb
<% set_meta_tags noindex: true %>


<div class="d-block mt-4"></div>
<%= render 'layouts/breadcrumb', items_hash: @breadcrumb_hash %>

<div class="container bg-white pt-5 pb-5 my-5">

  <div class="row justify-content-md-center">

    <div class="col-md-6">

      <h1 class="font-weight-bold mb-5"><%= title @title %></h1>
      <%= render 'subscriptions/item', subscription: @subscription %>

      <%= link_to "追加購入する", checkout_unit_purchases_path(subscription_id: @subscription.id),
                  class: 'btn btn-solid main-loading-show-btn w-100',
                  data: { "turbolinks" => false } %>


      <div class="d-block py-5"></div>
      <% if @unit_purchases.present? %>
        <h1 class="font-weight-bold mt-5 mb-5"><%= '追加購入履歴' %></h1>

        <%= render partial: 'unit_purchases/item', collection: @unit_purchases, as: "unit_purchase" %>


      <% end %>


      <div class="d-block py-5"></div>


    </div>
  </div>
</div>