config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root to: 'static_pages#home'
    post '/create-checkout-session', to: 'static_pages#create-checkout-session'


    mount Sidekiq::Web => '/sidekiq'
    mount ActionCable.server => '/cable'

    # APIとサービスの「認証情報」の設定
    get '/auth/google_oauth2/callback', to: 'static_pages#home'
    get  '/signup',  to: 'users#new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    # 資料請求
    get '/catalog_request', to: 'static_pages#catalog_request'

    # 2020/10/21 letter_opener 導入
    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: '/letter_opener'
    end

    resources :users do
      member do
        get :payment_setting
        get :invoices
      end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]

    resources :plans do
      collection do
        get :introduction
      end
    end
    resources :units

    # 支払い方法
    resources :customers do
      member do
        #支払い方法の削除の確認
        get :delete_confirmation
      end
      collection do
        get :fix_payment_method
      end
    end

    # 定期課金
    resources :subscriptions do
      collection do
        get :checkout
        get :success
      end
      member do
        patch :cancel
      end
    end

    # 都度購入
    resources :unit_purchases do
      collection do
        get :checkout
        get :success
      end
    end

    resources :webhook do
      collection do
        post :stripe
      end
    end


  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  # belongs_to :user, optional: true
  has_many   :subscriptions, dependent: :destroy
  # Planに登録しているユーザー一覧
  has_many :subscribers, through: :subscriptions, source: :user
  # 追加料金
  has_one :unit
  validates :stripe_price_id, presence: true
  # before_destroy :delete_stripe_plan, prepend: true

  #validates :nickname, presence: true
  # validates :amount,   presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 100, less_than_or_equal_to: 10_000 }
  #validates :trial_period_days, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 40 }

  def set_attributes_by_stripe_id
    stripe_plan = Stripe::Plan.retrieve(self.stripe_price_id) rescue nil
    self.currency = stripe_plan&.currency
    self.interval = stripe_plan&.interval
    self.usage_type = stripe_plan&.usage_type
  end

  def unix_time_trial_end
    return if trial_period_days.blank?

    end_date_str = Time.now.next_day(self.trial_period_days).to_s
    Time.parse(end_date_str).to_i
  end


  # 無料お試し期間
  def trial_period_days_count
    if trial_period_days.present? && trial_period_days > 1
      trial_period_days
    else
      nil
    end
  end


  def self.monthly_school
    find_by(reference_number: 1)
  end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  # dependent: :destroyの前に、before_destroyをおく。
  before_action :admin_user, only: %i[index new create edit update destroy]

  def index
    @plans = Plan.includes(:unit).order(reference_number: :asc)
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.set_attributes_by_stripe_id
    if @plan.save
      flash[:success] = 'Plan created'
      redirect_to plans_path
    else
      flash[:danger] = 'Creating Plan failed'
      render 'plans/new'
    end
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    @plan.set_attributes_by_stripe_id
    if @plan.update(plan_params)
      flash[:success] = 'Plan updated'
      redirect_to plans_path
    else
      flash[:danger] = 'Update failed'
      render 'plans/edit'
    end
  end

  def destroy
    #  @plan = Plan.find(params[:id])
    #  @stripe_plan_id = @plan.stripe_plan_id
    #  @plan.destroy
    #  flash[:danger] = 'プランを削除しました。'
    #  redirect_to plans_url
  end


  def introduction

  end



  private

  def plan_params
    # stripe_plan_idはparamsに含めない。
    params.require(:plan).permit(:stripe_price_id, :nickname, :amount, :trial_period_days, :reference_number)
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_cv_btn.html.erb
<tr>
  <td>
    <% if logged_in? %>
      <%= link_to '契約する', checkout_subscriptions_path(plan_number: number),
                  class: 'btn btn-solid main-loading-show-btn w-100',
                  data: { "turbolinks" => false } %>
    <% else %>
      <a class="btn move-to-catalog-request w-100" href="#">詳細はこちら</a>
    <% end %>
  </td>
</tr>

app/views/plans/_explanation_1.html.erb
<tr>
  <th>英作文添削(自由作文/長文要旨)</th>
</tr>
<tr>
  <td class="plan-price">3,000<span> 円／月</span><br>300<span>words</span></td>
</tr>
<tr>
  <td>テスト対策から日常生活まで</td>
</tr>
<tr>
  <td>長文要約/自由作文も対応</td>
</tr>
<tr>
  <td><b>字数制限の範囲なら何回でもOK</b></td>
</tr>
<tr>
  <td>優秀な外大生が添削・コメント</td>
</tr>
<tr>
  <td><b>+2500円ごとに300words追加可能</b></td>
</tr>

app/views/plans/_explanation_2.html.erb
<tr>
  <th>英語(文法、読解)</th>
</tr>
<tr>
  <td class="plan-price">10,000<span> 円／月</span><br>100<span>分</span></td>
</tr>
<tr>
  <td>個々の学習計画に基づく個別指導</td>
</tr>
<tr>
  <td>日程は講師と都度相談</td>
</tr>
<!--
<tr>
  <td><b>料金は時間で決定</b></td>
</tr>
<tr>
  <td><b>追加受講も時間単位で可能</b></td>
</tr>
-->
<tr>
  <td>教材は生徒様に合わせて決定</td>
</tr>
<tr>
  <td><b>+7000円ごとに100分の追加講義</b></td>
</tr>

app/views/plans/_explanation_3.html.erb
<tr>
  <th>英会話</th>
</tr>
<tr>
  <td class="plan-price">10,000~<span> 円／月</span><br>80<span>分</span></td>
</tr>
<tr>
  <td>日常会話から入試対策まで</td>
</tr>
<tr>
  <td>海外滞在経験/留学経験のある講師</td>
</tr>
<tr>
  <td>時間はライフスタイルに合わせて</td>
</tr>
<tr>
  <td>学習目的に合わせた指導内容</td>
</tr>
<tr>
  <td><b>+7000円ごとに80分の追加講義</b></td>
</tr>

app/views/plans/_form.html.erb
<%= form_with model: plan, local: true do |f| %>

  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :stripe_price_id, "stripe_price_id", class: 'item-label my-3' %>
  <%= f.text_field :stripe_price_id, class: "form-control", placeholder: 'price_xxxxx' %>

  <%= f.label :nickname, "nickname", class: 'item-label my-3' %>
  <%= f.text_field :nickname, class: "form-control", placeholder: 'Plan Name' %>

  <%= f.label :amount, "amount", class: 'item-label my-3' %>
  <%= f.number_field :amount, class: "form-control", placeholder: 'Amount' %>

  <%= f.label :trial_period_days, "trial_period_days", class: 'item-label my-3' %>
  <%= f.number_field :trial_period_days, class: "form-control", placeholder: 'trial_period_days' %>

  <%= f.label :reference_number, "reference_number", class: 'item-label my-3' %>
  <%= f.number_field :reference_number, class: "form-control" %>

  <%= f.submit "OK", class: "btn btn-solid w-100 my-5 main-loading-show-btn" %>

<% end %>

app/views/plans/_item.html.erb
<% stripe_plan = Stripe::Plan.retrieve(plan.stripe_price_id) rescue nil %>
<div class="col-sm-6 my-3">

  <div class="card">
    <div class="card-header">
      ID: <%= plan.id %> / ReferenceNumber: <%= plan.reference_number %>
    </div>
    <div class="card-body">
      <% if stripe_plan.present? %>
        <h5 class="card-title">nickname: <b><%= plan.nickname %></b></h5>
        <p class="card-text">amount: <b><%= plan.amount %></b></p>
        <p class="card-text">trial_period_days: <b><%= plan.trial_period_days %></b></p>
        <p class="card-text">currency: <b><%= plan.currency %></b></p>
        <p class="card-text">interval: <b><%= plan.interval %></b></p>
        <p class="card-text">usage_type: <b><%= plan.usage_type %></b></p>
        <p class="card-text">Subscribers: <%= plan.subscribers.count %></p>
        <button class="btn btn-sm btn-border-gray w-100 text-center mb-3" type="button" data-toggle="collapse" data-target="#collapse-<%= plan.id %>" aria-expanded="false" aria-controls="collapseExample">
          JSON
        </button>
        <div class="collapse py-4" id="collapse-<%= plan.id %>">
          <p class="card-text"><%= stripe_plan.to_s %></p>
        </div>
      <% else %>
        <h5 class="card-title">Invalid ID</h5>
      <% end %>
      <% if (unit = plan.unit) %>
        <%= link_to "Unit: #{unit.amount}", edit_unit_path(unit), class: 'btn btn-success w-100' %>
      <% else %>
        <%= link_to 'Add Unit', new_unit_path(plan_id: plan.id), class: 'btn btn-success w-100' %>
      <% end %>

      <%= link_to 'Edit Plan', edit_plan_path(plan), class: 'btn btn-success w-100' %>



    </div>
  </div>
</div>

app/views/plans/_price_list.html.erb
<div class="plans mt-5">
  <div class="flexbox">
    <div class="plan-table plan-free px-2">
      <table>
        <%= render 'plans/explanation_1' %>
        <%= render 'plans/cv_btn', number: 1 %>
      </table>
    </div>
    <div class="plan-table plan-premium px-2">
      <table>
        <%= render 'plans/explanation_2' %>
        <%= render 'plans/cv_btn', number: 2 %>
      </table>
    </div>

    <div class="plan-table plan-premium px-2">
      <table>
        <%= render 'plans/explanation_3' %>
        <%= render 'plans/cv_btn', number: 3 %>
      </table>
    </div>
  </div>
</div>

app/views/plans/edit.html.erb
<% set_meta_tags noindex: true %>

<div class="container bg-white pt-5 pb-5 my-5">
  <div class="row justify-content-md-center">
    <div class="col-md-6">
      <h1 class="my-3"><%= title "Edit Plan" %></h1>
      <%= render 'plans/form', plan: @plan %>
    </div>
  </div>
</div>

app/views/plans/index.html.erb
<% set_meta_tags noindex: true %>
<!--
使わなくなったプランも出来るだけ削除はしないでおくようにする。
詳しくは、<a href="https://stripe.com/docs/billing/subscriptions/products-and-plans#managing-products-and-plans" target="_blank" rel="noopener">ドキュメント</a>を参照</p>
-->

<div class="container bg-white pt-5 pb-5 my-5 px-5">

  <h1 class="text-center">Plan</h1>

  <div class="row row-height">
    <%= render partial: "plans/item", collection: @plans, as: 'plan' %>
  </div>

  <%= link_to new_plan_path, class: "btn btn-solid w-100 my-5" do %>
    <i class="far fa-plus"></i>Add Plan
  <% end %>

</div>

app/views/plans/new.html.erb
<% set_meta_tags noindex: true %>

<div class="container bg-white pt-5 pb-5 my-5">
  <div class="row justify-content-md-center">

    <div class="col-md-6">

      <h1 class="my-3"><%= title "Add Plan" %></h1>

      <%= render 'plans/form', plan: @plan %>

    </div>

  </div>

</div>